name: Playwright Tests
on:
  push:
    branches: [main]
  workflow_dispatch:
    description: 'manual trigger'
  # pull_request:
  #   branches: [main, master]
  # https://crontab.guru/
  # below cron config will run the workflow at 16:30 on the 3rd day of every month
  schedule:
    - cron: '30 16 3 * *' # At 03:00 on Monday
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --pass-with-no-tests

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 4
